my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_list, name='home'),
    path('password-reset/', include('password_reset.urls')),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

userprofile/models.py
from django.db import models
from django.contrib.auth.models import User


# user info
class Profile(models.Model):
    # user and model is one to one relation
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    # phone number
    phone = models.CharField(max_length=20, blank=True)
    # avatar
    avatar = models.ImageField(upload_to='avatar/%Y%m%d/', blank=True)
    # bio
    bio = models.TextField(max_length=500, blank=True)

    def __str__(self):
        return 'user {}'.format(self.user.username)

userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class UserRegisterForm(UserCreationForm):
    # add email as defail user create form
    email = forms.EmailField(label = "Email")

    class Meta:
        model = User
        fields = ('username', 'email',)


# User profile
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ('phone', 'avatar', 'bio')

userprofile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse

from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .forms import UserLoginForm, UserRegisterForm

from .forms import ProfileForm
from .models import Profile


# Create your views here.

# user login
def user_login(request):
    if request.method == 'POST':
        user_login_form = UserLoginForm(data=request.POST)
        if user_login_form.is_valid():
            data = user_login_form.cleaned_data
            # check if account and password match the user in the database
            # if so return this user object
            user = authenticate(username=data['username'], password=data['password'])
            if user:
                # store user data into "seesion" so the user will be in 
                # login status
                login(request, user)
                return redirect("article:article_list")
            else:
                return HttpResponse("The username or password is incorrectly. Please try again")
        else:
            return HttpResponse("Invalid account or password input")
    elif request.method == 'GET':
        user_login_form = UserLoginForm()
        context = { 'form': user_login_form }
        return render(request, 'account/login.html', context)
    else:
        return HttpResponse("Please use GET or POST method to request data")


def user_logout(request):
    logout(request)
    return redirect("article:article_list")


def user_register(request):
    if request.method == 'POST':
        user_register_form = UserRegisterForm(data=request.POST)
        if user_register_form.is_valid():
            new_user = user_register_form.save()
            # Return to the blog home page onece register inform was stored
            login(request, new_user)
            return redirect("article:article_list")
        else:
            # the defaul form has "check" funtion that check of password vaild, and many other inform, like complxity, etc.
            return HttpResponse("Password is invalid, please make sure entered a password meets the standard!")
    elif request.method == 'GET':
        user_register_form = UserRegisterForm()
        context = { 'form': user_register_form }
        return render(request, 'account/signup.html', context)
    else:
        return HttpResponse("Please use GET or POST method to request data")


# delete user
# A decorator that validates the if the user is logged in
@login_required(login_url='/accounts/login/')
def user_delete(request, id):
    if request.method == 'POST':
        user = User.objects.get(id=id)
        # Verify that the logged in user and the user to be deleted are the same
        if request.user == user:
            #logout, delete the user data and return to blog home page
            logout(request)
            user.delete()
            return redirect("article:article_list")
        else:
            return HttpResponse("You do not have permission to delete the account!")
    else:
        return HttpResponse("Only POST request is acceptable!")


# Edit user profile
@login_required(login_url='/accounts/login/')
def profile_edit(request, id):
    user = User.objects.get(id=id)

    # get the profile
    if Profile.objects.filter(user_id=id).exists():
        profile = Profile.objects.get(user_id=id)
    else:
        profile = Profile.objects.create(user=user)


    if request.method == 'POST':
        # check if the user is vaild
        if request.user != user:
            return HttpResponse("You do not have permission to modify this user profile!")

        # save the upload file in request.FILES, and use paramenter to transfter to the form object
        profile_form = ProfileForm(request.POST, request.FILES)

        if profile_form.is_valid():
            # get the data after clearning
            profile_cd = profile_form.cleaned_data

            profile.phone = profile_cd['phone']
            profile.bio = profile_cd['bio']

            # if request.FILES have files, save
            if 'avatar' in request.FILES:
                profile.avatar = profile_cd["avatar"]

            profile.save()
            return redirect("userprofile:edit", id=id)
        else:
            return HttpResponse("The registration form was entered incorrectly. Please try again!")

    elif request.method == 'GET':
        profile_form = ProfileForm()
        context = { 'profile_form': profile_form, 'profile': profile, 'user': user }
        return render(request, 'userprofile/edit.html', context)
    else:
        return HttpResponse("Please use POST/GET to request data")

templates/userprofile/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block head_title %} {% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" >
</head>
<body>

  <main>
      <div class="container">
      {% block content %}
      {% endblock %}
    </div>
  </main>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

</body>
</html>

templates/userprofile/edit.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} User Profile {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <div class="col-md-4">Username: {{ user.username }}</div>
            <br>
            {% if profile.avatar %}
                <div class="col-md-4">Avatar</div>
                <img src="{{ profile.avatar.url }}" style="max-width: 20%; border-radius: 15%;" class="col-md-4">
            {% else %}
                <h5 class="col-md-4">No avatar yet</h5>
            {% endif %}
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                {% csrf_token %}
                <!-- avatar -->
                <div class="form-group col-md-4">
                    <label for="avatar">Upload avatar</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <!-- phone -->
                <div class="form-group col-md-4">
                    <label for="phone">Phone</label>
                    <input type="text" class="form-control" id="phone" name="phone" value="{{ profile.phone }}">
                </div>
                <!-- bio -->
                <div class="form-group col-md-4">
                    <label for="bio">Bio</label>
                    <textarea type="text" class="form-control" id="bio" name="bio" rows="12">{{ profile.bio }}</textarea>
                </div>
   
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/login.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} login {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <h5>Don't have account yet?</h5>
            <h5><a href='{% url "userprofile:register" %}'> Register </a></h5>
            <br>
            <form method="post" action=".">
                {% csrf_token %}
                <div class="form-group col-md-4">
                    <label for="username">username</label>
                    <input type="text" class="form-control" id="username" name="username">
                </div>
        
                <div class="form-group col-md-4">
                    <label for="password">password</label>
                    <input type="password" class="form-control" id="password" name="password">
                </div>
        
                <button type="submit" class="btn btn-primary">submit</button>
            </form>
            <br>
            <h5>Password Forgot? </h5>
            <h5>Click <a href='{% url "password_reset_recover" %}'> here </a> reset password</h5>
        </div>
    </div>
</div>
{% endblock content %}

templates/userprofile/register.html
{% extends "base.html" %} {% load staticfiles %}
<!-- Need to install bootstrap4 and add to installed apps in settings.py -->
{% load bootstrap4 %}
{% block title %} Sign up {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                {% buttons %}
                <button type="submit" class="btn btn-primary">Submit</button>
                {% endbuttons %}
            </form>
        </div>
    </div>
</div>
{% endblock content %}