article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    # article list
    path('article-list/', views.article_list, name='article_list'),
    # article detail
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # write article
    path('article-create/', views.article_create, name='article_create'),
    # delete article
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # safe delete article
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # update article
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # like ++
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),
    # list view
    path('list-view/', views.ArticleListView.as_view(), name='list_view'),
    # list view detail
    path('detail-view/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_view'),
    # create list view
    path('create-view/', views.ArticleCreateView.as_view(), name='create_view'),
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_list, name='home'),
    path('password-reset/', include('password_reset.urls')),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

templates/back_to_top_func.html
<!-- Reference: -->
<!-- https://ezbox.idv.tw/131/back-to-top-button-without-images -->
<button type="button" id="BackTop" class="toTop-arrow" style="z-index: 100;"></button>

<script>
    // funtion row back to top
    $(function () {
        $('#BackTop').click(function () {
            $('html,body').animate({scrollTop: 0}, 500);
        });
        $(window).scroll(function () {
            if ($(this).scrollTop() > 300) {
                $('#BackTop').fadeIn(300);
            } else {
                $('#BackTop').stop().fadeOut(300);
            }
        }).scroll();
    });
</script>

<style>
    /* 按钮边框的大小、位置、样式 */
    .toTop-arrow {
        width: 3.5rem;
        height: 3.5rem;
        padding: 0;
        margin: 0;
        border: 0;
        border-radius: 33%;
        opacity: 0.7;
        background: black;
        cursor: pointer;
        position: fixed;
        right: 1.5rem;
        bottom: 1.5rem;
        display: none;
    }

    /* 绘制按钮中的向上箭头 */
    .toTop-arrow::before, .toTop-arrow::after {
        width: 31px;
        height: 7px;
        border-radius: 3px;
        background: orange;
        position: absolute;
        content: "";
    }

    .toTop-arrow::before {
        transform: rotate(-45deg) translate(0, -50%);
        left: 0.4rem;
    }

    .toTop-arrow::after {
        transform: rotate(45deg) translate(0, -50%);
        right: 0.4rem;
    }

    /* 取消点击按钮时的聚焦 */
    .toTop-arrow:focus {
        outline: none;
    }
</style>

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<!-- set to cn-zh for chinese -->
<html lang="en-us">

<head>
    <!-- encode use, use utf-8 to capable chinese -->
    <meta charset="utf-8">
    <!-- Title -->
    <title>{% block title %}{% endblock %}</title>
    <!-- load css file in bootstrap -->
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- load monikai.css -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">

    <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.14.0/css/all.min.css"
    >
</head>

<body>

<!-- load header-->
{% include 'header.html' %}
<!-- leave some space -->
<div id="wrapper">
    {% block content %}{% endblock content %}
    <div id="push"></div>
</div>
<!-- load fotter-->
{% include 'footer.html' %}

<!-- bootstrap.js needs jquery.js  and popper.js, import them here -->
<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>

<!-- removely use popper.js-->
{#<script src="{% static 'popper/popper-1.14.4.js' %}"></script>#}
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1-lts/dist/umd/popper.min.js"></script>

<!-- load js file from bootstrap -->
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<!-- load layer.js -->
<script src="{% static 'layer/layer.js' %}"></script>

{% block script %}{% endblock script %}

{% include 'back_to_top_func.html' %}


<style>
    html, body {
        height: 100%;
        margin: 0;
    }

    #wrapper {
        min-height: 100%;
        margin-bottom: -40px;
    }

    #footer,
    #push {
        height: 60px;
    }
</style>

</body>

</html>

templates/footer.html
{% load staticfiles %}
<!-- Footer -->
<footer class="py-3 bg-dark" id="footer">
    <div class="container">
        <h5 class="m-0 text-center text-white">Power by django &copy; Deploy on AWS EC2</h5>
        
    </div>
</footer>

templates/header.html
{% load notifications_tags %}
{% notifications_unread as unread_count %}

<!-- define navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <!-- define navbar-brand -->
        <a class="navbar-brand" href="#">Django Based Blog</a>
        
        <div>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'article:article_list' %}">Article</a>
                </li>

                {% if user.is_authenticated %}
                    <!-- show user name if user has logged in -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8"
                                     width="8px"
                                     height="8px">
                                    <circle cx="4"
                                            cy="4"
                                            r="4"
                                            fill="#ff6b6b"
                                    ></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "notice:list" %}">Notice
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{% url 'article:article_create' %}">Write Article</a>
                            <a class="dropdown-item" href='{% url "userprofile:edit" user.id %}'>User Info</a>
                            <a class="dropdown-item" href="#" onclick="user_delete()">Delete User</a>
                            <a class="dropdown-item" href='{% url "userprofile:logout" %}'>Log Out</a>
                        </div>
                    </li>
                <!-- show login if not already login -->
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

{% if user.is_authenticated %}
<form 
    style="display:none;" 
    id="user_delete"
    action="{% url 'userprofile:delete' user.id %}" 
    method="POST"
>
{% csrf_token %}
    <button type="submit">Submit</button>
</form>
    <script>
        function user_delete() {
            // user layer plugin
            layer.open({
                title: "Delete confirmation",
                content: "Are you sure you want to delete this user?",
                yes: function(index, layero) {
                    $('form#user_delete button').click();
                    layer.close(index);
                },
            })
        }
    </script>
{% endif %}