article/urls.py
from django.urls import path
from . import views

app_name = 'article'

urlpatterns = [
    # article list
    path('article-list/', views.article_list, name='article_list'),
    # article detail
    path('article-detail/<int:id>/', views.article_detail, name='article_detail'),
    # write article
    path('article-create/', views.article_create, name='article_create'),
    # delete article
    path('article-delete/<int:id>/', views.article_delete, name='article_delete'),
    # safe delete article
    path('article-safe-delete/<int:id>/', views.article_safe_delete, name='article_safe_delete'),
    # update article
    path('article-update/<int:id>/', views.article_update, name='article_update'),
    # like ++
    path('increase-likes/<int:id>/', views.IncreaseLikesView.as_view(), name='increase_likes'),
    # list view
    path('list-view/', views.ArticleListView.as_view(), name='list_view'),
    # list view detail
    path('detail-view/<int:pk>/', views.ArticleDetailView.as_view(), name='detail_view'),
    # create list view
    path('create-view/', views.ArticleCreateView.as_view(), name='create_view'),
]

comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    # post comment
    path('post-comment/<int:article_id>', views.post_comment, name='post_comment'),
    path('post-comment/<int:article_id>/<int:parent_comment_id>', views.post_comment, name='comment_reply')
]

my_blog/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import notifications.urls

from article.views import article_list


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', article_list, name='home'),
    path('password-reset/', include('password_reset.urls')),
    path('article/', include('article.urls', namespace='article')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    path('comment/', include('comment.urls', namespace='comment')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('notice.urls', namespace='notice')),
    path('accounts/', include('allauth.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

userprofile/urls.py
from django.urls import path
from . import views

app_name = 'userprofile'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('delete/<int:id>/', views.user_delete, name='delete'),
    path('edit/<int:id>/', views.profile_edit, name='edit'),
]

article/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager

# use to handle the images
from PIL import Image

class ArticleColumn(models.Model):

    title = models.CharField(max_length=100, blank=True)
    
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class ArticlePost(models.Model):
    """
    Post Article Model
    """


    author = models.ForeignKey(User, on_delete=models.CASCADE)


    avatar = models.ImageField(upload_to='article/%Y%m%d/', blank=True)


    column = models.ForeignKey(
        ArticleColumn,
        null=True,
        blank=True,
        on_delete=models.CASCADE,
        related_name='article'
    )

    # use Django-taggit lib
    tags = TaggableManager(blank=True)


    # title
    title = models.CharField(max_length=100)

    
    body = models.TextField()

    # view number
    total_views = models.PositiveIntegerField(default=0)

    # likes
    likes = models.PositiveIntegerField(default=0)

    # posting times
    created = models.DateTimeField(default=timezone.now)

    # post last modified time
    updated = models.DateTimeField(auto_now=True)

    class Meta:
    	# '-created': reverse order 
        ordering = ('-created',)

    def __str__(self):
        return self.title

    # get the address of the article
    def get_absolute_url(self):
        return reverse('article:article_detail', args=[self.id])

    # handle the images
    def save(self, *args, **kwargs):
        # handle the size of image
        article = super(ArticlePost, self).save(*args, **kwargs)

        if self.avatar and not kwargs.get('update_fields'):
            image = Image.open(self.avatar)
            (x, y) = image.size
            new_x = 400
            new_y = int(new_x * (y / x))
            resized_image = image.resize((new_x, new_y), Image.ANTIALIAS)
            resized_image.save(self.avatar.path)

        return article

    def was_created_recently(self):
        # if post in the last 60 seconds it defines as recently
        diff = timezone.now() - self.created
        
        # if diff.days <= 0 and diff.seconds < 60:
        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            return True
        else:
            return False

article/forms.py
from django import forms
from .models import ArticlePost

class ArticlePostForm(forms.ModelForm):
    class Meta:
        model = ArticlePost
        fields = ('title', 'body', 'tags', 'avatar')

article/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.http import HttpResponse
from .models import ArticlePost, ArticleColumn
from .forms import ArticlePostForm
import markdown
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from comment.models import Comment
from comment.forms import CommentForm
from django.views import View
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView


def article_list(request):
    # get infor fron url
    search = request.GET.get('search')
    order = request.GET.get('order')
    column = request.GET.get('column')
    tag = request.GET.get('tag')

    # search article
    article_list = ArticlePost.objects.all()

    # search article
    if search:
        article_list = article_list.filter(
            Q(title__icontains=search) |
            Q(body__icontains=search)
        )
    else:
        # if not search make it empty
        search = ''

    # column
    if column is not None and column.isdigit():
        article_list = article_list.filter(column=column)

    # tage
    if tag and tag != 'None':
        article_list = article_list.filter(tags__name__in=[tag])

    # order
    if order == 'total_views':
        # order by number of views
        article_list = article_list.order_by('-total_views')

    # shows 5 article each page
    paginator = Paginator(article_list, 5)
    # get page number from url
    page = request.GET.get('page')
    # get page number to the article
    articles = paginator.get_page(page)
    context = {
        'articles': articles,
        'order': order,
        'search': search,
        'column': column,
        'tag': tag,
    }
    # return context to static page
    return render(request, 'article/list.html', context)


def article_detail(request, id):
    # get the article
    article = get_object_or_404(ArticlePost, id=id)
    
    # get commnets
    comments = Comment.objects.filter(article=id)

    # view++
    article.total_views += 1
    article.save(update_fields=['total_views'])

    # show neibor article 
    pre_article = ArticlePost.objects.filter(id__lt=article.id).order_by('-id')
    next_article = ArticlePost.objects.filter(id__gt=article.id).order_by('id')
    if pre_article.count() > 0:
        pre_article = pre_article[0]
    else:
        pre_article = None

    if next_article.count() > 0:
        next_article = next_article[0]
    else:
        next_article = None


    # use Markdown editor 
    md = markdown.Markdown(
        extensions=[
        'markdown.extensions.extra',
        'markdown.extensions.codehilite',
        'markdown.extensions.toc',
        ]
    )
    article.body = md.convert(article.body)

    comment_form = CommentForm()

    # return model for the context
    context = { 
        'article': article,
        'toc': md.toc,
        'comments': comments,
        'pre_article': pre_article,
        'next_article': next_article,
        'comment_form': comment_form,
    }
    return render(request, 'article/detail.html', context)


# create article(need user to login in order to post article)
@login_required(login_url='/accounts/login/')
def article_create(request):
    # determine if user post article, if so put the infor into form that
    # meet the data type requirnemnt, and set the author to the login user
    # and save all those to the data base
    if request.method == "POST":
        article_post_form = ArticlePostForm(request.POST, request.FILES)
        if article_post_form.is_valid():
            new_article = article_post_form.save(commit=False)
            new_article.author = User.objects.get(id=request.user.id)
            if request.POST['column'] != 'none':
                new_article.column = ArticleColumn.objects.get(id=request.POST['column'])
            new_article.save()
            article_post_form.save_m2m()
            return redirect("article:article_list")
        else:
            return HttpResponse("Content invalid, please change the content!")
    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = { 'article_post_form': article_post_form, 'columns': columns }
        return render(request, 'article/create.html', context)


# delete article, vulnerable for csrf attack
@login_required(login_url='/accounts/login/')
def article_delete(request, id):
    article = ArticlePost.objects.get(id=id)
    if request.user != article.author:
        return HttpResponse("You do not have permission to modify this post!")
    article.delete()
    return redirect("article:article_list")


# safe delete, this method can prevent csrf attack
@login_required(login_url='/accounts/login/')
def article_safe_delete(request, id):
    if request.method == 'POST':
        article = ArticlePost.objects.get(id=id)
        if request.user != article.author:
            return HttpResponse("You do not have permission to modify this post!")
        article.delete()
        return redirect("article:article_list")
    else:
        return HttpResponse("Only allow POST requests")


# update article
@login_required(login_url='/accounts/login/')
def article_update(request, id):
    """
    bascally overwrite the views(article title, content, etc.) of the article, 
    and use post method to submit article form again.
    """
    article = ArticlePost.objects.get(id=id)

    if request.user != article.author:
        return HttpResponse("You do not have permission to modify this post!")

    if request.method == "POST":
        article_post_form = ArticlePostForm(data=request.POST)
        if article_post_form.is_valid():
            article.title = request.POST['title']
            article.body = request.POST['body']
            if request.POST['column'] != 'none':
                article.column = ArticleColumn.objects.get(id=request.POST['column'])
            else:
                article.column = None

            if request.FILES.get('avatar'):
                article.avatar = request.FILES.get('avatar')

            article.tags.set(*request.POST.get('tags').split(','), clear=True)
            article.save()
            return redirect("article:article_detail", id=id)
        else:
            return HttpResponse("ontent invalid, please change the content!")

    else:
        article_post_form = ArticlePostForm()
        columns = ArticleColumn.objects.all()
        context = { 
            'article': article, 
            'article_post_form': article_post_form,
            'columns': columns,
            'tags': ','.join([x for x in article.tags.names()]),
        }
        return render(request, 'article/update.html', context)


# likes ++
class IncreaseLikesView(View):
    def post(self, request, *args, **kwargs):
        article = ArticlePost.objects.get(id=kwargs.get('id'))
        article.likes += 1
        article.save()
        return HttpResponse('success')


def article_list_example(request):
    if request.method == 'GET':
        articles = ArticlePost.objects.all()
        context = {'articles': articles}
        return render(request, 'article/list.html', context)



class ContextMixin:
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['order'] = 'total_views'
        return context


class ArticleListView(ContextMixin, ListView):
    context_object_name = 'articles'
    template_name = 'article/list.html'
    def get_queryset(self):
        queryset = ArticlePost.objects.filter(title='Python')
        return queryset


class ArticleDetailView(DetailView):
    queryset = ArticlePost.objects.all()
    context_object_name = 'article'
    template_name = 'article/detail.html'

    def get_object(self):
        obj = super(ArticleDetailView, self).get_object()
        obj.total_views += 1
        obj.save(update_fields=['total_views'])
        return obj

class ArticleCreateView(CreateView):
    model = ArticlePost
    fields = '__all__'
    template_name = 'article/create_by_class_view.html'

templates/article/create.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} Write A Post {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                <!-- csrf_token is needed every time used post -->
                {% csrf_token %}

                <div class="form-group">
                    <label for="avatar">Title Image</label>
                    <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" 
                           class="form-control" 
                           id="title" 
                           name="title"
                    >
                </div>
                
                <div class="form-group">
                    <label for="column">Category</label>
                    <select class="form-control col-3" 
                            id="column" 
                            name="column"
                    >
                            <option value="none">Select category..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}">{{ column }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                    <label for="tags">Tags</label>
                    <input type="text" 
                           class="form-control col-3" 
                           id="tags" 
                           name="tags"
                    >
                </div>

                <div class="form-group">
                    <label for="body">Content</label>
                    <textarea type="text" 
                              class="form-control" 
                              id="body" 
                              name="body" 
                              rows="12"
                    ></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

templates/article/create_by_class_view.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
</form>

templates/article/detail.html
{% extends "base.html" %}
{% load staticfiles %}

{% block title %}
Article Details
{% endblock title %}

{% block content %}
<script src="{% static 'ckeditor/ckeditor/plugins/prism/lib/prism/prism_patched.min.js' %}"></script>
<link rel="stylesheet" href="{% static 'prism/prism.css' %}">

<div class="container">
    <div class="row">
        <div class="col-9">
            <h1 class="mt-4 mb-4">{{ article.title }}</h1>
            <div class="alert alert-success">
                <div>
                    Author：{{ article.author }}
                    {% if user == article.author %}

                        · <a href="#" onclick="confirm_safe_delete()">Delete</a>
                        <form 
                            style="display:none;" 
                            id="safe_delete"
                            action="{% url 'article:article_safe_delete' article.id %}" 
                            method="POST"
                        >
                        {% csrf_token %}
                            <button type="submit">Submit</button>
                        </form>

                        · <a href="{% url "article:article_update" article.id %}">
                            Edit
                        </a>
                    {% endif %}
                </div>
                <div>
                    View：{{ article.total_views }}
                </div>
            </div>

            <div class="col-12">
                <p>{{ article.body|safe }}</p>
            </div>

            <div style="text-align:center;" class="mt-4">
                <button class="btn btn-outline-danger"
                        type="button"
                        onclick="validate_is_like(
                                '{% url 'article:increase_likes' article.id %}',
                                {{ article.id }},
                                {{ article.likes }}
                            )"
                >
                    <span>Likes</span>
                    <span>
                        <i class="fas fa-heart"></i>
                    </span>
                    <span id="likes_number">
                        {{ article.likes }}
                    </span>
                </button>
            </div>

            <br>
            <div class="row justify-content-end">
                {% if next_article %}
                <div class="col-auto mr-auto">
                    <a  href="{{ next_article.get_absolute_url }}" 
                        class="btn btn-info"
                        >
                        {{ next_article.title }}
                    </a>
                </div>
                {% endif %}
            {% if pre_article %}
                <div class="col-auto">
                    <a  href="{{ pre_article.get_absolute_url }}" 
                    class="btn btn-info" 
                    >
                        {{ pre_article.title }}
                    </a>
                </div>
            {% endif %}
            </div>


            <!-- Comment -->
            <hr>
            {% if user.is_authenticated %}
                <div>
                    <form 
                        action="{% url 'comment:post_comment' article.id %}" 
                        method="POST"
                    >
                    {% csrf_token %}
                        <div class="form-group">
                            <label for="body">
                                <strong>
                                    Make Comment：
                                </strong>
                            </label>
                            <div>
                                {{ comment_form.media }}
                                {{ comment_form.body }}
                            </div>
                        </div>
                        <!-- Submit bottom -->
                        <button type="submit" class="btn btn-primary ">Submit</button>
                    </form>
                </div>
                <br>
            {% else %}
                <br>
                <h5 class="row justify-content-center">
                    <a href="{% url 'userprofile:login' %}"> Login </a>
                </h5>
                <br>
            {% endif %}
            


            <!-- Comment shows -->
            {% load mptt_tags %}
            <h4>Totally {{ comments.count }} Comments</h4>
            <div class="row">
                <!-- Go through tree structure -->
                {% recursetree comments %}
                    {% with comment=node %}
                        <div class="{% if comment.reply_to %}
                                    offset-1 col-11
                                    {% else %}
                                    col-12
                                    {% endif %}"
                            id="comment_elem_{{ comment.id }}" 
                        >
                            <hr>
                            <p>
                                <strong style="color: pink">
                                    {{ comment.user }}
                                </strong> 

                                <!-- show people being replied -->
                                {% if comment.reply_to %}
                                    <i class="far fa-arrow-alt-circle-right" 
                                       style="color: cornflowerblue;"
                                    ></i>
                                    <strong style="color: pink">
                                        {{ comment.reply_to }}
                                    </strong> 
                                {% endif %}

                            </p>
                            <div>{{ comment.body|safe }}</div>

                            <div>
                                <span style="color: gray">
                                    {{ comment.created|date:"Y-m-d H:i" }}
                                </span>

                                <!-- load model bittom -->
                                {% if user.is_authenticated %}
                                    <button type="button" 
                                            class="btn btn-light btn-sm text-muted" 
                                            onclick="load_modal({{ article.id }}, {{ comment.id }})"
                                    >
                                        reply
                                    </button>
                                {% else %}
                                    <a class="btn btn-light btn-sm text-muted" 
                                        href="{% url 'userprofile:login' %}"
                                    >
                                        reply
                                    </a>
                                {% endif %}
                            </div>

                            <!-- Modal -->
                            <div class="modal fade" 
                                 id="comment_{{ comment.id }}" 
                                 tabindex="-1" 
                                 role="dialog" 
                                 aria-labelledby="CommentModalCenter" 
                                 aria-hidden="true"
                            >
                                <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                    <div class="modal-content" style="height: 480px">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalCenterTitle">reply {{ comment.user }}：</h5>
                                        </div>
                                        <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                    </div>
                                </div>
                            </div>

                            {% if not comment.is_leaf_node %}
                                <div class="children">
                                    {{ children }}
                                </div>
                            {% endif %}
                        </div>
                        
                    {% endwith %}
                {% endrecursetree %}
            </div>  
        </div>

        <!-- Table of contents -->
        <div class="col-3 mt-4" id="sidebar" class="sidebar">
            <div class="sidebar__inner">
                <h4><strong>Contents</strong></h4>
                <hr>
                <div>
                    {{ toc|safe }}
                </div>
            </div>
        </div>
    </div>
</div>

<!-- side style -->
<style>
    .sidebar{
        will-change: min-height;
    }

    .sidebar__inner{
        transform: translate(0, 0); /* For browsers don't support translate3d. */
        transform: translate3d(0, 0, 0);
        will-change: position, transform;
    }
</style>

<script>
    // delete post funtion
    function confirm_delete() {
        layer.open({
            title: "Confirm Deletion",
            content: "Are you sure you want to delete this post?",
            yes: function(index, layero) {
                location.href='{% url "article:article_delete" article.id %}'
            },
        })
    }

    function confirm_safe_delete() {
        layer.open({
            title: "Confirm Deletion",
            content: "Are you sure you want to delete this post?",
            yes: function(index, layero) {
                $('form#safe_delete button').click();
                layer.close(index);
            }
        })
    }
</script>
{% endblock content %}

{% block script %}

<!-- csrf token -->
<script src="{% static 'csrf.js' %}"></script>
<script>
    // like funtion
    function validate_is_like(url, id, likes) {
        // take out LocalStorage data
        let storage = window.localStorage;
        const storage_str_data = storage.getItem("my_blog_data");
        let storage_json_data = JSON.parse(storage_str_data);
        // create empty dir if not data exist
        if (!storage_json_data) {
            storage_json_data = {}
        };
        //const status = check_status(storage_json_data, id);
        //if (status) {
        //    layer.msg('already liked');
        //    return;
        //} else {
            // use Jquery to find like number and then  +1
        $('span#likes_number').text(likes + 1).css('color', '#dc3545');
        //}
        // use ajax to post request
        $.post(
            url,

            {},
            function(result) {
                if (result === 'success') {
                    
                    try {
                        storage_json_data[id] = true;
                    } catch (e) {
                        window.localStorage.clear();
                    };

                    const d = JSON.stringify(storage_json_data);
                    
                    try {
                        storage.setItem("my_blog_data", d);
                    } catch (e) {
                        // code 22 means LocalStorage full
                        if (e.code === 22) {
                            window.localStorage.clear();
                            storage.setItem("my_blog_data", d);
                        }
                    };
                } else {
                    layer.msg("Failed to communicate with the server. Try again later");
                }

            }
        );
    };
    
    function check_status(data, id) {
        
        try {
            if (id in data && data[id]) {
                return true;
            } else {
                return false;
            }
        } catch (e) {
            window.localStorage.clear();
            return false;
        };
    };
</script>

<script src="{% static 'sticky_sidebar/jquery.sticky-sidebar.min.js' %}"></script>
<script type="text/javascript">
    $('#sidebar').stickySidebar({
        topSpacing: 20,
        bottomSpacing: 20,
    });
</script>

<script>
    $(".django-ckeditor-widget").removeAttr('style');
</script>

<!-- seconary replay modal -->
<script>
    // load modal
    function load_modal(article_id, comment_id) {
        let modal_body = '#modal_body_' + comment_id;
        let modal_id = '#comment_' + comment_id;

        // load editor
        if ($(modal_body).children().length === 0) {
            let content = '<iframe src="/comment/post-comment/' + 
                article_id + 
                '/' + 
                comment_id + 
                '" frameborder="0" style="width: 100%; height: 100%;"></iframe>';
            $(modal_body).append(content);
        };

        $(modal_id).modal('show');
    };

    // handle secondary replay
    function post_reply_and_show_it(new_comment_id) {
        let next_url = "{% url 'article:article_detail' article.id %}";

        next_url = next_url.charAt(next_url.length - 1) == '/' ? next_url.slice(0, -1) : next_url;

        window.location.replace(next_url + "#comment_elem_" + new_comment_id);
    };
</script>
{% endblock script %}

templates/article/tag_list.html
<ul>
{% for comment in comments %}
    <li> {{ comment.created }} </li>
{% endfor %}
</ul>

templates/article/update.html
{% extends "base.html" %} {% load staticfiles %}
{% block title %} 更新文章 {% endblock title %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <br>
            <form method="post" action="." enctype="multipart/form-data">
                <!-- Django that use POST data need to have csrf_token -->
                {% csrf_token %}

                <div class="form-group">
                    <label for="title">Title</label>
                    <input type="text" class="form-control" id="title" name="title" value="{{ article.title }}">
                </div>

                <div class="form-group">
                    <label for="column">Category</label>
                    <select class="form-control" 
                            id="column" 
                            name="column"
                    >
                            <option value="none">Select category..</option>
                        {% for column in columns %}
                            <option value="{{ column.id }}"
                                {% if column.id == article.column.id %}
                                    selected
                                {% endif %}
                            >
                                {{ column }}
                            </option>
                        {% endfor %}
                    </select>
                </div>

                <div class="form-group">
                   <label for="avatar">Title Image</label>
                   <input type="file" class="form-control-file" name="avatar" id="avatar">
                </div>

                <div class="form-group">
                     <label for="tags">Tags</label>
                     <input type="text" class="form-control col-3" id="tags" name="tags"
                        value="{{ tags }}">
                </div>

                <div class="form-group">
                    <label for="body">Content</label>
                    <textarea type="text" class="form-control" id="body" name="body" rows="12">{{ article.body }}</textarea>
                </div>

                <button type="submit" class="btn btn-primary">Post</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}